services:
  fountain:
    build:
      context: .
    restart: unless-stopped
    volumes:
      - data:/home/pytezos/data
      - ./credentials.json:/home/pytezos/credentials.json
    env_file:
      - .env
    networks:
      - indexer

volumes:
  data:

networks:
  indexer:
    external: true
